<?php

namespace App\Console\Commands;

use App\Support\Docs\RouteInventory;
use Illuminate\Console\Command;

class GenerateEndpointDocs extends Command
{
    protected $signature = 'app:endpoints';

    protected $description = 'Generate docs/endpoints.md — an inventory of every application route.';

    public function handle(RouteInventory $inventory): int
    {
        $entries = $inventory->entries();

        $rows = collect($entries)->map(fn (array $e) => sprintf(
            '| `%s` | `%s` | %s | %s | `%s` |',
            $e['methods'],
            $e['uri'],
            $e['name'] ?? '—',
            $e['permission'] ?? '—',
            $e['action'],
        ))->implode("\n");

        $markdown = "# Endpoints\n\n"
            .'All application routes (Inertia + API), generated by `php artisan app:endpoints`. '
            ."For JSON API schema docs see `/docs/api` (Scramble).\n\n"
            ."| Method | URI | Name | Permission | Controller |\n"
            ."|---|---|---|---|---|\n"
            .$rows."\n";

        file_put_contents(base_path('docs/endpoints.md'), $markdown);

        $this->info('Wrote docs/endpoints.md ('.count($entries).' endpoints).');

        return self::SUCCESS;
    }
}
